trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  ARM_TENANT_ID: $(ARM_TENANT_ID)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

jobs:
- job: terraform
  displayName: 'Terraform Import, Plan, and Apply'
  steps:
  - checkout: self

  - script: |
      terraform init
    displayName: 'Terraform Init'

  - script: |
      # Import the existing resource into the Terraform state
      terraform import azurerm_resource_group.rg /subscriptions/a67fa08c-8a71-4843-a6e9-1fbd1d8198b6/resourceGroups/cloudresume
    displayName: 'Terraform Import Resource Group'

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
